"In this file are defined the main configurations of the game"
import random
import os

random.seed(12321)
# GLADIATOR VARIABLES
GLADIATOR_HEALTH = 100
GLADIATOR_STAMINA = 100
GLADIATOR_SPEED = 1
GLADIATOR_ATTACK_RANGE = 10
GLADIATOR_ATTACK_DAMAGE = 10


# SIMULATION VARIABLES
RADIAL_RESOLUTION = 10  # quantization of the direction in degrees
GLADIATOR_NAMES = [
    "A",
    "B",
]  # this list decide also the number of gladiators in the game
TIMER = 100  # max number of turns

# ARENA VARIABLE
ARENA_SIZE = 100

# REWARDS AND PENALTIES
WIN_REWARD = 100
SUCCESFULL_ATTACK_REWARD = 2
BLOCKED_ATTACK_REWARD = 2
KILL_REWARD = 10

HITTED_PENALTY = -2
MISSED_ATTACK_PENALTY = -0.25
TIMEOUT_PENALTY = -0.1
DEATH_PENALTY = -10
NO_STAMINA_PENALTY = -0.5
USELESS_REST_PENALTY = -0.2

# TRAINING VARIABLES
TRAINING_EPISODES = 2

# VISUALIZATION VARIABLES
VIEW = True
VIEW_EVERY = 10
FPS = 30
SCREEN_HEIGHT = 10
SCREEN_WIDTH = 10
ARENA_VISUALIZATION_SIZE = ARENA_SIZE
GLADIATOR_SIZE = ARENA_VISUALIZATION_SIZE * 0.01
STATS_BARS_HIGHT = GLADIATOR_SIZE / 3
STATS_BARS_LENGTH = GLADIATOR_SIZE * 5
LINE_SIZE = GLADIATOR_SIZE / 3
TIMER_POSITION = (ARENA_VISUALIZATION_SIZE / 2, ARENA_VISUALIZATION_SIZE * 0.8)
TIMER_RADIUS = ARENA_VISUALIZATION_SIZE * 0.1

# SAVING PATHS
BASE_PATH = os.path.dirname(os.path.abspath(__file__))
MODEL_SAVE_PATH = os.path.join(BASE_PATH, "models")
SIMUALTION_RECORD_PATH = os.path.join(BASE_PATH, "simulations_record")


# FIXED VARIABLES: can't be changed, inserted just for readability
NUM_POSSIBLE_ACTIONS = 5  # len(Gladiator.possible_actions)
